spring:
  datasource:
    url: jdbc:postgresql://10.0.0.9:5432/pgsql-bulk-index
    username: postgres
    password: postgres
    hikari:
      auto-commit: true
logging:
  level:
    root: error
    top.meethigher.test: info